### ISSUE TITLE
Any further developments?

### ISSUE THREAD

**Issue by RandomMaerks** [keepsjh/teriyake#4]
Hi! Thank you for creating this beautiful typeface.

I see that the project hasn't been updated for a year, and I'm wondering if there's any future plans for it.

**Comment by the3ash** [comment]
> Hi! Thank you for creating this beautiful typeface.
> 
> I see that the project hasn't been updated for a year, and I'm wondering if there's any future plans for it.

As an exercise piece it looks so bad to me nowadays that I'll consider a complete redesign later on, if I have time.
